# export CUDA_VISIBLE_DEVICES=5
python -u all_train.py \
    -data processed_data/all-train \
    -save_model experiments/all_train/model \
    -seed 42  \
    -gpu_ranks 0 \
    -save_checkpoint_epochs 1 \
    -keep_checkpoint 500 \
    -train_epochs 500 \
    -report_every 50000 \
    -param_init 0  \
    -param_init_glorot \
    -max_generator_batches 32 \
    -batch_size 64 \
    -batch_type sents \
    -normalization tokens \
    -max_grad_norm 0 \
    -accum_count 4 \
    -optim adam \
    -adam_beta1 0.9 \
    -adam_beta2 0.998 \
    -decay_method noam \
    -warmup_steps 32  \
    -learning_rate 0.1 \
    -label_smoothing 0.0 \
    -layers 4 \
    -rnn_size 256 \
    -word_vec_size 256 \
    -dropout 0.1 \
    -position_encoding \
    -share_embeddings \
    -global_attention general \
    -global_attention_function softmax \
    -self_attn_type scaled-dot \
    -heads 8 \
    -transformer_ff 2048 \
    -log_file all_train.log
